using VirtualPetSimulator.Models;

Console.WriteLine(CatAscii.PlayfulCat);
await Task.Delay(2000);
Console.Clear();
Console.WriteLine(CatAscii.SleepingCat);
await Task.Delay(2000); 
Console.Clear();
Console.WriteLine(CatAscii.PeepingCat);
Console.ReadKey();
Console.Clear();
Console.WriteLine(CatAscii.SittingCat);
Console.ReadKey();
Console.Clear();
Console.WriteLine(CatAscii.SittingCat2);
Console.ReadKey();
Console.Clear();
Console.WriteLine(CatAscii.LayingCat);
Console.ReadKey();
Console.Clear();
Console.WriteLine(CatAscii.CatInBox);
Console.ReadKey();